name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run -a --hook-stage push
      - name: Setup tests
        run: |
          make setup-tests
      - name: Run tests
        run: |
          pytest
